language: php

before_script:
  - if ! git show-ref --quiet master; then
      git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/* ;
      git fetch --tags ;
      git branch master origin/master ;
    fi
  - composer install

# see https://github.com/travis-ci/travis-ci/issues/4942#issuecomment-159132444
git:
  depth: 99999

jobs:
  include:
    #- stage: Static analysis (src) with phpstan
    #  php: 7.2
    #  script: vendor/bin/phpstan analyse --level=7 src

    - stage: Test
      php: 7.2
      script: vendor/bin/phpunit

    - stage: Code Coverage
      php: 7.2
      before_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - composer install
      script:
        - vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml

    - stage: Coding Standards
      php: 7.2
      script: vendor/bin/phpcs

    #- stage: Mutation Tests
    #  php: 7.2
    #  script: vendor/bin/infection

    - stage: Verify BC Breaks
      php: 7.2
      script: bin/roave-backward-compatibility-check --from=master --to=HEAD

cache:
  directories:
    - $HOME/.composer/cache
